Add support for cargo
1Password/shell-plugins pull request #139
Opened 2023-01-09 18:40 UTC by accraw

Currently don't have the test passing for importing credentials from a file, working on that now.

If I change [registry] to [[registry]] it passes, but that's not how the file is created by cargo. 

Resolves #81

2023-01-10 13:11 UTC, volodymyrZotov requested changes

2023-01-10 13:13 UTC, volodymyrZotov commented
Hey @accraw ! Thank you for your contribution!
It's very good! Looks like we are almost there.

I reviewed your PR and added some comments that might help you to fix the tests and finalize the PR.

2023-01-10 13:13 UTC, florisvdg commented on plugins/cargo/api_token.go
> +				MarkdownDescription: "Token used to authenticate to Cargo.",
Should this be:
```suggestion
				MarkdownDescription: "Token used to authenticate to crates.io.",
```

2023-01-10 13:13 UTC, florisvdg commented on plugins/cargo/cargo.go
> +		NeedsAuth: needsauth.NotForHelpOrVersion(),
Not for help and for version, but I'm guessing also only for these commands:
- `cargo publish`
- `cargo owner`
- `cargo yank`

2023-01-10 13:19 UTC, florisvdg commented on plugins/cargo/api_token.go
> +			})
(as described in #81's "Goal or desired behavior" section)

2023-01-10 19:10 UTC, accraw commented on plugins/cargo/api_token.go
> +			})
Now that I'm looking more at it, we may want to just support crates.io due to the following: 

The token for [crates.io](https://crates.io/) may be specified with the CARGO_REGISTRY_TOKEN environment variable. Tokens for other registries may be specified with environment variables of the form CARGO_REGISTRIES_<name>_TOKEN where <name> is the name of the registry in all capital letters.

@florisvdg do you know if we have a way to support the use case for dynamic environment variables right now?

2023-01-10 19:17 UTC, florisvdg commented on plugins/cargo/api_token.go
> +			})
You'd have to write your own `sdk.Provisioner` implementation to do that. But we could also do that in a follow-up PR and for now just stick with crates.io support.

2023-01-11 12:08 UTC, volodymyrZotov approved these changes

2023-01-11 12:26 UTC, florisvdg commented on plugins/cargo/api_token.go
> +			NameHint: importer.SanitizeNameHint("crates.io"),
Given that it's always a `crates.io` token, I don't think it's necessary to add a hint in the item name.
```suggestion
```

2023-01-11 14:02 UTC, florisvdg approved these changes

2023-01-11 14:27 UTC, volodymyrZotov approved these changes

2023-01-11 14:28 UTC, merged